[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'hotchpotch/perldoc-vim'

#[[plugins]]
#repo = 'hokaccha/vim-perllocallib'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
'''

[[plugins]]
repo = 'xolox/vim-misc'
if = 0

[[plugins]]
repo = 'xolox/vim-session'
depends = 'vim-misc'
if = 0
hook_source = '''
let g:session_autosave = 'yes'
'''
